### ISSUE TITLE
Some messages could not be processed: 'MissingTopic'

### ISSUE THREAD

**Issue by rocchidavide** [django-push-notifications/django-push-notifications#432]
Trying to send a test notification I obtain:

`Some messages could not be processed: 'MissingTopic'`

Application id is empty. The only setting I set is APNS_CERTIFICATE.

django-push-notifications 1.5.0
Django 1.11.6
DRF 3.4.6

**Comment by matthewh** [comment]
@rocchidavide DPNS is designed to support a single "application" unless you enable [Multiple-Application-Support](https://github.com/jleclanche/django-push-notifications/wiki/Multiple-Application-Support). It is OK for application_id to be empty in this case because DPNS will default to the only one available. It sounds like you need to add **APNS_TOPIC** to your configuration.
